#!/bin/bash

bytes=0
echo -n "Shellcode: "
for i in `objdump -d $1 | tr '\t' ' ' | tr ' ' '\n' | egrep '^[0-9a-f]{2}$' ` ; 
do
    echo -n "\x$i";
    bytes=$((bytes + 1))
done
echo
echo "Len: $bytes"
